<?php

namespace ContainerAvVwleW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rqa4ydwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rqa4ydw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rqa4ydw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CustomerController::index' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\LuxuryController::createLuxuryCar' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ShoppingController::add' => ['privates', '.service_locator.EXuYPsb', 'get_ServiceLocator_EXuYPsbService', true],
            'App\\Controller\\ShoppingController::delete' => ['privates', '.service_locator.EXuYPsb', 'get_ServiceLocator_EXuYPsbService', true],
            'App\\Controller\\ShoppingController::index' => ['privates', '.service_locator.EXuYPsb', 'get_ServiceLocator_EXuYPsbService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CustomerController:index' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\LuxuryController:createLuxuryCar' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ShoppingController:add' => ['privates', '.service_locator.EXuYPsb', 'get_ServiceLocator_EXuYPsbService', true],
            'App\\Controller\\ShoppingController:delete' => ['privates', '.service_locator.EXuYPsb', 'get_ServiceLocator_EXuYPsbService', true],
            'App\\Controller\\ShoppingController:index' => ['privates', '.service_locator.EXuYPsb', 'get_ServiceLocator_EXuYPsbService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CustomerController::index' => '?',
            'App\\Controller\\LuxuryController::createLuxuryCar' => '?',
            'App\\Controller\\ShoppingController::add' => '?',
            'App\\Controller\\ShoppingController::delete' => '?',
            'App\\Controller\\ShoppingController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CustomerController:index' => '?',
            'App\\Controller\\LuxuryController:createLuxuryCar' => '?',
            'App\\Controller\\ShoppingController:add' => '?',
            'App\\Controller\\ShoppingController:delete' => '?',
            'App\\Controller\\ShoppingController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
