<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXALi4c2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXALi4c2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXALi4c2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXALi4c2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXALi4c2\App_KernelDevDebugContainer([
    'container.build_hash' => 'XALi4c2',
    'container.build_id' => 'fc48fcd5',
    'container.build_time' => 1646331586,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXALi4c2');
