<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHdkwrVi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHdkwrVi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHdkwrVi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHdkwrVi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHdkwrVi\App_KernelDevDebugContainer([
    'container.build_hash' => 'HdkwrVi',
    'container.build_id' => 'c078d97d',
    'container.build_time' => 1646337808,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHdkwrVi');
